### ISSUE TITLE
Op Mac: hij pakt niet de ë (52.2 Afvoeren, fecaliën)

### ISSUE THREAD

**Issue by tiesdemoel** [BIM-Tools/SketchUp-IFC-Manager#11]
He Jan, goed bezig!
Ik krijg het niet voor elkaar om bijvoorbeeld 52.2 toe te voegen, kak!
Als ik de skc apart laadt, zie ik ook een gek tekentje op de plek van de ë....
<img width="1401" alt="Schermafbeelding 2019-12-16 om 17 16 06" src="https://user-images.githubusercontent.com/7418469/70923195-c4747000-2027-11ea-8f69-9bd2f4cceae2.png">

**Comment by janbrouwer** [comment]
Je hebt gelijk! Goed dat je het doorgeeft.
Probleempje met character encoding. Dan ben je waarschijnlijk de eerste die een riolering geclassificeerd heeft ;-)
Moet wel makkelijk te fixen zijn, ga ik naar kijken!

**Comment by janbrouwer** [comment]
Finally fixed this encoding error, thanks to your contributed skc!
https://github.com/BIM-Tools/SketchUp-IFC-Manager/commit/534bf2cd602ad5201f1debab2418add03e31b950

**Comment by tiesdemoel** [comment]
En dat op mijn verjaardag!!

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Jan Brouwer <notifications@github.com>
Verzonden: Saturday, January 9, 2021 10:45:27 AM
Aan: BIM-Tools/SketchUp-IFC-Manager <SketchUp-IFC-Manager@noreply.github.com>
CC: Jack de Moel <jack_de_moel@msn.com>; Author <author@noreply.github.com>
Onderwerp: Re: [BIM-Tools/SketchUp-IFC-Manager] Op Mac: hij pakt niet de ë (52.2 Afvoeren, fecaliën) (#11)


Closed #11<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBIM-Tools%2FSketchUp-IFC-Manager%2Fissues%2F11&data=04%7C01%7C%7Cba5d58dd31e64df32c0408d8b4834c69%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637457823295254179%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gOpNNtAPRKF0VwSy6y9gXG%2Bc6sqwAqKIqiH9eLwADnA%3D&reserved=0>.
