### ISSUE TITLE
how to install SketchUp-IFC-Manager ? 

### ISSUE THREAD

**Issue by RichardPinka** [BIM-Tools/SketchUp-IFC-Manager#12]
Hello, maybe I am just blind... 
can You please describe me the way how do I install this plugin to my Sketchup ? 
thank You in forward

**Comment by Benjaminkl1** [comment]
Hi Rick,

Just go to the wiki page and click installation.

Regards,

Ben

**Comment by Hodepinemannen** [comment]
well, there's a download button, but not an install button. And the downloaded file is a package file. I tried renaming the zip-file to a .rbz file, but extension manager would not read it. Inside the package there is no .rbz file. So I think the question is legitimate :-)

**Comment by Hodepinemannen** [comment]
all right, sorry. I guess one has to know ones way around GitHub. There's a link to "releases" on the page, and clicking on the release there will download the .rbz file, and then you can install it from extension manager. It does not show up as installed before you restart sketchup, but that's more of a sketchup problem.

**Comment by nnijmeijer** [comment]
Hi All,

You can download the IFC Manager from the Releases page.
[]((https://github.com/BIM-Tools/SketchUp-IFC-Manager/releases))

It is important that you download the .RBZ file. 
You can then install this extension in SketchUp via the Extension Manager.

**Comment by janbrouwer** [comment]
Ah yes you are right, github is not the most enduser-friendly platform, more focused on software development.
On the releases page you indeed need to open the "Assets" dropdown and then download the .rbz file.
I will look at the wiki page, I might be able to make the instructions a bit more elaborate.

**Comment by Hodepinemannen** [comment]
My first try was to download the code, and that obviously was not the right thing to do :-)

mvh
Odd Håkon Byberg

siv ark Odd Håkon Byberg AS
Nordregt. 8
7011 Trondheim
tlf 96 22 77 66
odd.byberg@me.com <mailto:odd.byberg@me.com>

**Comment by janbrouwer** [comment]
I updated the installation instructions, I hope this helps!
https://github.com/BIM-Tools/SketchUp-IFC-Manager/wiki/Installation
