### ISSUE TITLE
Filter added in NL SfB

### ISSUE THREAD

**Issue by tiesdemoel** [BIM-Tools/SketchUp-IFC-Manager#13]
Added a filter file for simplification :) Wanna try?

[NL-SfB 2005 tabel 1.skc.zip](https://github.com/BIM-Tools/SketchUp-IFC-Manager/files/4244387/NL-SfB.2005.tabel.1.skc.zip)

**Comment by janbrouwer** [comment]
Interessant! @SvSchaijk wat denk jij daarvan? Een simplyfy filter om tussen 3 en 4 cijferig NL-SfB te schakelen...

**Comment by janbrouwer** [comment]
I updated the NL-SfB classification with your contributed version with filter and character encoding fixes! Thanks!
https://github.com/BIM-Tools/SketchUp-IFC-Manager/commit/534bf2cd602ad5201f1debab2418add03e31b950
