### ISSUE TITLE
Add custom skc

### ISSUE THREAD

**Issue by tiesdemoel** [BIM-Tools/SketchUp-IFC-Manager#14]
He Jan, wat moet ik doen om een customised skc in de UI te laten verschijnen?
(Ik weet, ik moet leren ruby:)
Ik kan het handlen om er een in te laden, maar dat is niet schaalbaar, natuurlijk.
fijner zou zijn om er een uit de 'In Model>Classifications' te kiezen en die te laden in IFC Manager.
Thoughts?

**Comment by janbrouwer** [comment]
Ik heb nog geen manier gevonden om helemaal zonder code de mapping van een sketchup classification naar een ifc classification te doen. Wat wil je precies doen? Een extra classificatie systeem toevoegen? Of de bestaande NL-SfB verbeteren?

**Comment by tiesdemoel** [comment]
Mmm ja, is eigenlijk de bedoeling dat SketchUp dat zelf voor elkaar boxed maar tot die tijd...
Ik had bijvoorbeeld een eigen systeempje proberen op te zetten:

[Projects.skc.zip](https://github.com/BIM-Tools/SketchUp-IFC-Manager/files/4245095/Projects.skc.zip)

Maar, zoals verwacht komt er bij de export niets in IFC van de attributen. Ook van gewone SketchUp bestanden worden de Attributen niet weergegeven in Trimble Connect.

Ik ben een case aan het opbouwen, Trimble heeft onlangs een webinar gehouden over de workflow extensions (Ik heb ook een Premium!). Ik ben aan het kijken hoe de opbouw in SketchUp dan dient te zijn.
Ik ga de Amerikaanse standaard die ze daar voor calculatie gebruiken als xml opzetten, en dan kijken of ik die in de IFC-Manager kan krijgen zonder al teveel ingewikkelde dingen (basically copy paste in bestaande .skc)

Ik wil eigenlijk een hele simpele opbouw van mijn SketchUp model, en dan direct in Trimble Connect aan de slag.

**Comment by janbrouwer** [comment]
Amerikaanse standaard? uniformat assembly code misschien? Als je een goed werkende skc hebt wil ik wel even kijken of hij makkelijk in de plugin te krijgen is, ik heb ook de classificatie voor de Duitse DIN norm van @maltepalmen toegevoegd voor de nieuwe versie waar ik mee bezig ben.

**Comment by tiesdemoel** [comment]
Nu, ik dacht aan de NAHB, lekker simpel voor huizenbouwers, ik kwam daar mee in aanraking met Estimator4SketchUp van John Brock, om de boys from Boulder een beetje te kietelen :)


Met vriendelijke groet,

Jack
______________________________
•••••••Verstuurd vanaf locatie••••••
______________________________
Jack de Moel

Stationsstraat 57  1541 LG
Koog aan de Zaan
T +31 6 23096432
E info@jackdemoel.nl
W www.jackdemoel.nl

Op 24 feb. 2020 om 16:15 heeft Jan Brouwer <notifications@github.com> het volgende geschreven:

﻿

Amerikaanse standaard? uniformat assembly code misschien? Als je een goed werkende skc hebt wil ik wel even kijken of hij makkelijk in de plugin te krijgen is, ik heb ook de classificatie voor de Duitse DIN norm van @maltepalmen<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmaltepalmen&data=02%7C01%7C%7C0615ff03f60841cd446c08d7b93c62ad%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637181541303670300&sdata=2LOrb53MGiahbmsayVsU7zM5clIX%2FzdIjjUggvl1nDI%3D&reserved=0> toegevoegd voor de nieuwe versie waar ik mee bezig ben.

**Comment by tiesdemoel** [comment]
heb een werkbare skc voor NAHB, filter (nog niet)
eigenlijk dezelfde opbouw als NLsfb
[NAHB.skc.zip](https://github.com/BIM-Tools/SketchUp-IFC-Manager/files/4359339/NAHB.skc.zip)
(dubbel gezipt)

**Comment by janbrouwer** [comment]
Hoi Jack,

Ik heb net een nieuwe testversie van de plugin online gezet waarbij het
makkelijker moet zijn om nieuwe classificaties toe te voegen.
Ik probeer snel even naar die van jou te kijken!

Groeten,
Jan

Op vr 20 mrt. 2020 om 12:58 schreef Jack de Moel <notifications@github.com>:

**Comment by MennoMekes** [comment]
Beste Jan,

ik heb de laatste versie en ik wil ook graag een eigen classificatie toevoegen.
Eigenlijk wil ik de NL-SfB, 2005 tabel 1 updaten naar die van 2019 of in ieder geval de naam van de IfcClassificationReference aanpassen naar de schrijfwijze zoals we voorstellen in tegel 3.6: NL-SfB tabel 1.

Als ik nu iets classificeer krijg ik er zelfs 2:
NL-SfB 2005, Tabel 1 én Uniformat Classification.
Die laatste wil ik sowieso niet.

**Comment by janbrouwer** [comment]
Hoi @MennoMekes,

Wat denk je van de door @nnijmijer aangepaste classificatie #28 ?
Je kunt het [skc bestand](https://github.com/BIM-Tools/SketchUp-IFC-Manager/pull/28/commits/361aca046095e2e5c7ed4bd98db5f2df66730fdb#diff-b82e6269dad5bf4d2c4b4e90e13a62e3fadc800daf0be939b312864f48f2dcbb) ook los inladen in sketchup om hem te testen, voldoet die ook aan jouw verwachtingen?

En dat je de unicode variant niet wilt snap ik heel goed, heb ik zelf ook liever niet maar die zit er in als workaround voor software die we bij VolkerWessels nodig hebben en die alleen op die rare plek zoekt. Ik zal kijken of ik daar een optie voor kan inbouwen waarmee dat uit te schakelen is want het geeft inderdaad ongewenste ruis voor de meeste IFC modellen.

**Comment by MennoMekes** [comment]
Hoi @janbrouwer, ja die is mooi. Ik had geprobeerd om eerst zelf de Classificatie-naam te veranderen maar dat werkte niet helemaal en toen had ik je plugin gesloopt. Nick had even snel dit gedaan en daarna nóg een extra toevoeging.

De toevoeging is de tekst 'Classification' erachter omdat Revit alle ClassificatioCode-parameters en ook de Assembly Code mapping exporteert naar de naar + 'Classification'. En dat is niet aan te passen.

Op dit moment ben ik de bestanden aan het updaten naar de NL-SfB Tabel 1 update december 2019. De huidige lijst is nog de 2005 lijst. (Vooral veel installatie aanpassingen maar PV-panelen bijvoorbeeld staan niet in de 2005 lijst. en nu wel, 61.15)
Als het klaar is upload ik deze ook.

**Comment by MennoMekes** [comment]
Ik heb de .yml en de .filter en .xsd aangepast naar de december 2019 update van de NL-SfB Tabel 1.
Wanneer ik deze bestanden op de juiste plaats zet werkt het niet meer

Ik heb de 3 bestanden ge-automatiseerd gemaakt. (Via Dynamo want dat snap ik)
Alleen het .filter-bestand in de skc snap ik niet helemaal, het lijkt alsof er in de originele niet de hele tabel zit.
En de spaties voor sommige accolades zien er random uit maar misschien is dat het wel.

[NL-SfB tabel 1 Classification.zip](https://github.com/BIM-Tools/SketchUp-IFC-Manager/files/7755773/NL-SfB.tabel.1.Classification.zip)

**Comment by tiesdemoel** [comment]
Er zitten wat foutjes in, de elementen worden niet correct afgesloten. Het filter file moet dezelfde naam krijgen met achter de extensie .xsd ‘.filter’ dus wordt dit ‘.xsd.filter’

Ik maak die zelf in Claris Filemaker, ik ga vanmiddag even aan de slag ermee

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Menno Mekes ***@***.***>
Verzonden: Tuesday, December 21, 2021 2:56:51 PM
Aan: BIM-Tools/SketchUp-IFC-Manager ***@***.***>
CC: Jack de Moel ***@***.***>; Author ***@***.***>
Onderwerp: Re: [BIM-Tools/SketchUp-IFC-Manager] Add custom skc (#14)


Ik heb de .yml en de .filter en .xsd aangepast naar de december 2019 update van de NL-SfB Tabel 1.
Wanneer ik deze bestanden op de juiste plaats zet werkt het niet meer

Ik heb de 3 bestanden ge-automatiseerd gemaakt. (Via Dynamo want dat snap ik)
Alleen het .filter-bestand in de skc snap ik niet helemaal, het lijkt alsof er in de originele niet de hele tabel zit.
En de spaties voor sommige accolades zien er random uit maar misschien is dat het wel.

NL-SfB tabel 1 Classification.zip<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBIM-Tools%2FSketchUp-IFC-Manager%2Ffiles%2F7755773%2FNL-SfB.tabel.1.Classification.zip&data=04%7C01%7C%7C9cdc0433607e4448732a08d9c489bddf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637756918139639500%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=K4EdpeheybRjuWWfvPKXQaX8VQTve2RktVt798TujWI%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBIM-Tools%2FSketchUp-IFC-Manager%2Fissues%2F14%23issuecomment-998799729&data=04%7C01%7C%7C9cdc0433607e4448732a08d9c489bddf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637756918139639500%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=SlYflY9S3y4TgjyHzTu2zvxeIslmTxa16kyPN9cPLo0%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABYTEZOLHDPP4IQJCYXJMPTUSCBSHANCNFSM4K2G2XHQ&data=04%7C01%7C%7C9cdc0433607e4448732a08d9c489bddf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637756918139639500%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Z2vjBiy1xKJCKHNEBYzNyrLizGbOkzTjSKto3hw7Txg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C9cdc0433607e4448732a08d9c489bddf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637756918139639500%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=10iTckqrW6frLzVhZWBxocJr4jZY1c7cQKoLXzPwwbQ%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C9cdc0433607e4448732a08d9c489bddf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637756918139639500%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Do9uqPSid5GRU9mxa3B%2B10Lo1KhwSSL4WhLJqlqb834%3D&reserved=0>.

**Comment by tiesdemoel** [comment]
[NL-SfB tabel 1 Classification.skc.zip](https://github.com/BIM-Tools/SketchUp-IFC-Manager/files/7767874/NL-SfB.tabel.1.Classification.skc.zip)

**Comment by MennoMekes** [comment]
Ja het is gelukt!
In het .xsd bestand ontbrak een flink stuk

          <xs:enumeration value="........................"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:element>
  

Dat had ik eerder moeten zien door het originele xsd en de nieuwe te vergelijken.
En op het eind was ik dit vergeten:

</xs:schema>

Verder zat er ook nog wat in het maken van de skc.
Ik had de map gezipped en niet de losse bestanden en de schema-map waardoor er een extra submap in zat.

Maar goed.
Nu is er dus de NL-SfB tabel 1 Classification met de huidige NL-SfB lijst, de update van december 2019.
Vooral heel veel veranderd en toegevoegd vanaf hoofdstuk 50.

[Sketchup NL-SfB tabel 1 update december 2019 bestanden.zip](https://github.com/BIM-Tools/SketchUp-IFC-Manager/files/7788178/Sketchup.NL-SfB.tabel.1.update.december.2019.bestanden.zip)

**Comment by janbrouwer** [comment]
> Maar goed. Nu is er dus de NL-SfB tabel 1 Classification met de huidige NL-SfB lijst, de update van december 2019. Vooral heel veel veranderd en toegevoegd vanaf hoofdstuk 50.

Goed werk @MennoMekes !

Lukt het jou om de aangepaste bestanden als een [PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) toe te voegen in de map https://github.com/BIM-Tools/SketchUp-IFC-Manager/tree/master/Sketchup%20classifications ?
Op die manier kunnen we mooi de wijzigingen bijhouden.

**Comment by janbrouwer** [comment]
Met de laatste updates moet het genoeg zijn om in het settings.yml bestand de nieuwe classificatie toe te voegen en zou hij meteen moeten werken. Als er geen .yml bestand bij de SKC zit pakt ie de lijst uit het .filter bestand uit de SKC.

**Comment by tiesdemoel** [comment]
Het filterbestand moet dezelfde naam krijgen als het hoofdschema met als toevoeging '.filter' dus 'NL-SfB tabel 1 Classification.xsd.filter
Die kan gewoon in de submap 'schemas' en compleet worden gecomprimeerd. Anders werkt het filter niet in de classifier tool. De 'simplify' option is dan niet zichtbaar.

**Comment by MennoMekes** [comment]
> Lukt het jou om de aangepaste bestanden als een [PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) toe te voegen in de map https://github.com/BIM-Tools/SketchUp-IFC-Manager/tree/master/Sketchup%20classifications ? Op die manier kunnen we mooi de wijzigingen bijhouden.

Ik ben niet genoeg thuis in Github om dat goed te doen.
We hebben een afspraak staan, als je het dan even kan laten zien dan kan ik het vanaf dan als pull request erin zetten.
