### ISSUE TITLE
Error message - export SketchUp-IFC-Manager 3.3.0

### ISSUE THREAD

**Issue by Wopklots** [BIM-Tools/SketchUp-IFC-Manager#18]
Hi Jan, 

While exporting I'm getting this Error - message:

Hash name: ifc bt manager options
Key: ifc_entities...... : ["IfcWindow", "IfcDoor", "IfcCurtainWall"]
Key: hidden............ : false
Key: hidden_layers..... : false
Key: attributes........ : []
Key: classifications... : true
Key: layers............ : true
Key: materials......... : true
Key: styles............ : true
Key: fast_guid......... : false
Key: dynamic_attributes : true
Created default IfcSite
Created default IfcBuilding
Created default IfcBuildingStorey
Error: #<NoMethodError: undefined method `add_related_element' for #<BimTools::IFC2X3::IfcBuildingStorey:0x000001f27d9111a0>
Did you mean?  add_related_object>
C:/Users/{USER}/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/IfcModel.rb:221:in `create_ifc_objects'
C:/Users/{USER}/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/IfcModel.rb:99:in `initialize'
c:/users/{USER}/appdata/roaming/sketchup/sketchup 2021/sketchup/plugins/rs_windowframes/csw_repo/scripts/ifc/ifc_export.rbe:105:in `new'
c:/users/{USER}/appdata/roaming/sketchup/sketchup 2021/sketchup/plugins/rs_windowframes/csw_repo/scripts/ifc/ifc_export.rbe:105:in `block in IFC_Export'
c:/users/{USER}/appdata/roaming/sketchup/sketchup 2021/sketchup/plugins/rs_windowframes/csw_repo/resources_general/libraries/rs/inputwebdialog_lib.rbe:178:in `block in InputWebDialog'

**Comment by janbrouwer** [comment]
Thanks for reporting this, that's indeed a bug because I changed that method. Is it possible to share your sketchup model? I think I fixed it but I can't replicate the error message.

**Comment by janbrouwer** [comment]
I made a new release version 3.4.1 with the changes, can you give that a try using that same model?

**Comment by Wopklots** [comment]
Hi Jan, 

I have tested with both versions and I see some changes in numbers of frames exported. But with the use of a viewer I'm seeing an empty document. No frames. The file is rather big. Can send it through wetransfer?

**Comment by janbrouwer** [comment]
The issue seems to be in filtering out IFC types with ifc_entities => ["IfcWindow", "IfcDoor", "IfcCurtainWall"]
Somehow when setting a filter it ignores all geometry.
It exports fine when using ifc_entities => false
I will look into it some more.

**Comment by janbrouwer** [comment]
I think I got it!
https://github.com/BIM-Tools/SketchUp-IFC-Manager/releases/tag/v3.4.2
Please re-open the issue when the problem is not resolved.
