### ISSUE TITLE
Exporting Windowframes gives empty file

### ISSUE THREAD

**Issue by Wopklots** [BIM-Tools/SketchUp-IFC-Manager#20]
Hi Jan,

I'm experiencing issues with the exporting of frames with the latest 3.4.5. version. 

3.4.5. export generates an empty file.

Exporting with 2.2.2. gave a frame-filled ifc. After updating to 3.4.5. an empty file is generated.
Both version are added in the attachments.
All settings were equal. The frames are exported as ifcCurtainWalls. 
I've also included the SKP in trying to export to IFC.
Any idea where the source of this issue lies? 
 
[Issue Export to ifc.zip](https://github.com/BIM-Tools/SketchUp-IFC-Manager/files/5987200/Issue.Export.to.ifc.zip)

![image](https://user-images.githubusercontent.com/77049526/108039121-f8885e00-703b-11eb-8797-09f752c4fdae.png)

**Comment by janbrouwer** [comment]
Thanks for reporting the issue!
It seems to be a problem in the exported ifc_entities. When I set it to the default "false" value (export all) then it seems to export fine. I will look into it!

**Comment by Wopklots** [comment]
I have something to add; everything goes great when using the BIMmanager button in your toolbar. When using it though the Construsoft Window menu (which directs the export through the Bim manager) I'm getting the issue with the empty ifc file. So it might as well be our own problem:o) Although you found a clue which might lead to a solution in your area of influence, but I figured this information might help:)

**Comment by janbrouwer** [comment]
This should be fixed: https://github.com/BIM-Tools/SketchUp-IFC-Manager/releases/tag/v3.4.6
