### ISSUE TITLE
IFC Export

### ISSUE THREAD

**Issue by bricks-me** [BIM-Tools/SketchUp-IFC-Manager#23]
Als ik via de plugin exporteer, gebeurt er niets meer nadat er gevraagd wordt het bestand een naam te geven. Hij maakt geen nieuw IFC aan

**Comment by nnijmeijer** [comment]
Dat is vervelend.
Als je de Ruby Console opent via het Window menu en vervolgens een IFC export maakt, zie je dan een foutmelding?
Zo ja, wat is de foutmelding die wordt weergegeven in de Ruby Console?

**Comment by bricks-me** [comment]
Product_su.rb:78:in `each'
C:/Users/no92/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/IfcProduct_su.rb:78:in `initialize'
C:/Users/no92/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/IFC2X3/IfcProduct.rb:34:in `initialize'
C:/Users/no92/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/IFC2X3/IfcElement.rb:32:in `initialize'
C:/Users/no92/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/IFC2X3/IfcBuildingElement.rb:32:in `initialize'
C:/Users/no92/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/IFC2X3/IfcBuildingElementProxy.rb:32:in `initialize'
C:/Users/no92/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/ObjectCreator.rb:94:in `new'
C:/Users/no92/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/ObjectCreator.rb:94:in `rescue in initialize'
C:/Users/no92/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/ObjectCreator.rb:71:in `initialize'
C:/Users/no92/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/IfcModel.rb:188:in `new'
C:/Users/no92/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/IfcModel.rb:188:in `create_ifc_objects'
C:/Users/no92/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/IfcModel.rb:103:in `initialize'
...

**Comment by bricks-me** [comment]
Sorry, niet hele tekst gekopieerd:
Error: #<NoMethodError: undefined method `id' for BimTools::IfcManager:Module>
C:/Users/no92/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/IfcRelDefinesByProperties_su.rb:134:in `eval'
C:/Users/no92/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/IfcRelDefinesByProperties_su.rb:134:in `eval'
C:/Users/no92/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/IfcRelDefinesByProperties_su.rb:134:in `block in initialize'
C:/Users/no92/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/IfcRelDefinesByProperties_su.rb:96:in `each'
C:/Users/no92/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/IfcRelDefinesByProperties_su.rb:96:in `initialize'
C:/Users/no92/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/IFC2X3/IfcRelDefinesByProperties.rb:34:in `initialize'
C:/Users/no92/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/IfcProduct_su.rb:120:in `new'
C:/Users/no92/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/IfcProduct_su.rb:120:in `block in initialize'
C:/Users/no92/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/IfcProduct_su.rb:78:in `each'
C:/Users/no92/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/IfcProduct_su.rb:78:in `initialize'
C:/Users/no92/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/IFC2X3/IfcProduct.rb:34:in `initialize'
C:/Users/no92/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/IFC2X3/IfcElement.rb:32:in `initialize'
C:/Users/no92/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/IFC2X3/IfcBuildingElement.rb:32:in `initialize'
C:/Users/no92/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/IFC2X3/IfcBuildingElementProxy.rb:32:in `initialize'
C:/Users/no92/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/ObjectCreator.rb:94:in `new'
C:/Users/no92/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/ObjectCreator.rb:94:in `rescue in initialize'
C:/Users/no92/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/ObjectCreator.rb:71:in `initialize'
C:/Users/no92/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/IfcModel.rb:188:in `new'
C:/Users/no92/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/IfcModel.rb:188:in `create_ifc_objects'
C:/Users/no92/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/IfcModel.rb:103:in `initialize'
...

**Comment by janbrouwer** [comment]
Bedankt voor het melden! Ik heb hem ook een keer gezien maar heb hem nog niet kunnen oplossen.
Welke versie gebruik je? Ik dacht dat deze melding alleen in de pre-release 3.5.0 tegen ben gekomen, en niet in de stabiele 3.4.7, kan dat kloppen?

**Comment by janbrouwer** [comment]
Ik ga er naar kijken, probeer in de tussentijd de 3.4.7 ;-)

**Comment by bricks-me** [comment]
OKe, kan je mij op weg helpen naar die versie. Waar kan ik die vinden?

**Comment by janbrouwer** [comment]
https://github.com/BIM-Tools/SketchUp-IFC-Manager/releases/download/v.3.4.7/bt_ifcmanager-3.4.7.rbz

**Comment by bricks-me** [comment]
Heb jij een suggestie hoe ik deze fout kan repareren?

**Comment by janbrouwer** [comment]
Je bedoeld de melding "IfcPositiveLengthMeasure must be a positive number!"?
Die zou ik gewoon negeren. Sommige velden zoals lengte en breedte in een propertyset mogen officieel niet "nul" zijn maar ik heb nog geen software gezien die daar moeilijk over doet. Als je bij alle objecten de properties invult is deze melding weg.
Misschien zou een verbetering in de exporter kunnen zijn om deze properties gewoon niet mee te exporteren als ze 0 zijn.

**Comment by pipauwel** [comment]
Volledig off-topic en 'an unsollicited opinion': Ik ben het er mee eens dat 'properties met waarde 0 of null of <empty>' achterwege zouden mogen blijven.
En meer tools zouden invalide data moeten rejecten, want met invalid files overal komen we maar matig verder.
Nu back on-topic 😄
________________________________
Van: Jan Brouwer ***@***.***>
Verzonden: donderdag 20 mei 2021 11:58
Aan: BIM-Tools/SketchUp-IFC-Manager ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: Re: [BIM-Tools/SketchUp-IFC-Manager] IFC Export (#23)


Je bedoeld de melding "IfcPositiveLengthMeasure must be a positive number!"?
Die zou ik gewoon negeren. Sommige velden zoals lengte en breedte in een propertyset mogen officieel niet "nul" zijn maar ik heb nog geen software gezien die daar moeilijk over doet. Als je bij alle objecten de properties invult is deze melding weg.
Misschien zou een verbetering in de exporter kunnen zijn om deze properties gewoon niet mee te exporteren als ze 0 zijn.

**Comment by janbrouwer** [comment]
> Volledig off-topic en 'an unsollicited opinion': Ik ben het er mee eens dat 'properties met waarde 0 of null of <empty>' achterwege zouden mogen blijven. En meer tools zouden invalide data moeten rejecten, want met invalid files overal komen we maar matig verder. Nu back on-topic 😄
> […](#)
> ________________________________ Van: Jan Brouwer ***@***.***> Verzonden: donderdag 20 mei 2021 11:58 Aan: BIM-Tools/SketchUp-IFC-Manager ***@***.***> CC: Subscribed ***@***.***> Onderwerp: Re: [BIM-Tools/SketchUp-IFC-Manager] IFC Export (#23) Je bedoeld de melding "IfcPositiveLengthMeasure must be a positive number!"? Die zou ik gewoon negeren. Sommige velden zoals lengte en breedte in een propertyset mogen officieel niet "nul" zijn maar ik heb nog geen software gezien die daar moeilijk over doet. Als je bij alle objecten de properties invult is deze melding weg. Misschien zou een verbetering in de exporter kunnen zijn om deze properties gewoon niet mee te exporteren als ze 0 zijn. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBIM-Tools%2FSketchUp-IFC-Manager%2Fissues%2F23%23issuecomment-844936925&data=04%7C01%7C%7C0ed90ccf4e81464ddc7308d91b75e016%7Ccc7df24760ce4a0f9d75704cf60efc64%7C1%7C0%7C637571015341976431%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hQUxFkB7XVF2o%2BuKRZlp9O0s5F21znM%2FdKNYv38pVHc%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAMOXUV23MMRSJHKQT76CULTOTMNZANCNFSM45GLAYHQ&data=04%7C01%7C%7C0ed90ccf4e81464ddc7308d91b75e016%7Ccc7df24760ce4a0f9d75704cf60efc64%7C1%7C0%7C637571015341976431%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BXksOwnpNj6ODKxbLyXmDatz%2BFismWY19IkzDcdM0fs%3D&reserved=0>.

Ja mee eens 😄
