### ISSUE TITLE
Export from IfcSystem does not export the Value in the Name attribute

### ISSUE THREAD

**Issue by simondilhas** [BIM-Tools/SketchUp-IFC-Manager#24]

**Comment by janbrouwer** [comment]
Thanks for reporting this

**Comment by janbrouwer** [comment]
Should be fixed in the next release: [Added attributes export to IfcGroup (Zone, System)](https://github.com/BIM-Tools/SketchUp-IFC-Manager/commit/33c85623cf3ac41813042575cce58bd76fbc08ac)
