### ISSUE TITLE
Components within components inside are not exported ok

### ISSUE THREAD

**Issue by rafhik** [BIM-Tools/SketchUp-IFC-Manager#36]
I have components that in previous versions were exported well and now only the components inside them are exported.
As an example a window classified as IfcWindow does not appear well in the Ifc file and all its interior elements appear as IFCElementProxy but none of them were clasified
![Captura de pantalla 2022-03-14 a las 20 30 37](https://user-images.githubusercontent.com/62211918/158248050-e32082d8-c498-4c49-ad33-09dc32cee586.jpg)
![Captura de pantalla 2022-03-14 a las 20 31 12](https://user-images.githubusercontent.com/62211918/158248095-337d432b-cbf8-433a-a755-1fa85c5a9c85.jpg)
![Captura de pantalla 2022-03-14 a las 20 33 29](https://user-images.githubusercontent.com/62211918/158248107-6da7f34e-0975-404d-a487-730ae634d902.jpg)

Version 4.1.4

**Comment by janbrouwer** [comment]
I was able to reproduce this, that is a big issue, I will look into it.

**Comment by janbrouwer** [comment]
This issue should be fixed. When you still encounter this problem with the next release, please re-open this issue!
