### ISSUE TITLE
Tags not exporting anymore

### ISSUE THREAD

**Issue by valleyarchitect** [BIM-Tools/SketchUp-IFC-Manager#38]
Hi, I've been using v 3.50 with no issues in particular & wanted to try v 4.15.  I tried it with both SU 2021 & 2022, but with both I no longer got any tags, or layers, exported with the ifc file.  In the older version I was charmed to see all our Tags/layers show up in eveBIM, the ifc viewer that we use... & I did check that the option to export tags as ifc layers is activated in the preferences... Maybe i'm doing something wrong ?

here in the .zip are the su file + the exports using the two versions of manager...

Thanks

**Comment by janbrouwer** [comment]
I get IFC layers with the current master version, so I hope this issue is fixed. When you still encounter this problem with the next release, please re-open this issue!

**Comment by valleyarchitect** [comment]
Hi,

Perfect, thanks, I'll check it out !

Best regards,
Patrick Thomas
architecte dplg
*T: +33(0)610045410*

http://www.vivarchi.f <http://www.vivarchi.fr>r
