### ISSUE TITLE
Tags not exporting anymore - v4-20

### ISSUE THREAD

**Issue by valleyarchitect** [BIM-Tools/SketchUp-IFC-Manager#39]
Hi, I just tested v4-20 & for some reason the tags/layers still do not export.  I tried in both Su21 & 22 & had the same result...
Maybe it's just me ?

**Comment by janbrouwer** [comment]
Can you share a model that I can test with?

**Comment by valleyarchitect** [comment]
Hi, yes of course:
[Documents.zip](https://github.com/BIM-Tools/SketchUp-IFC-Manager/files/9422149/Documents.zip).

**Comment by janbrouwer** [comment]
Thanks! I see a Layer attached to nearly all of the objects in test IFC model in my viewers.
That the layers are no longer visible in eveBIM could have something to do with the new options I added for more efficient IFC files:
- Export IFC Type products
- Export IFC Type properties
- Export IFC mapped items
When you enable mapped items for example, the layer gets attached to the mapped geometry instead.
Can you do another test with all these 3 options disabled?

**Comment by valleyarchitect** [comment]
Hi, yes, I tried that, but sadly still no layer/tags showing up in eveBIM :
[testIFCmanager4-20-again.zip](https://github.com/BIM-Tools/SketchUp-IFC-Manager/files/9442775/testIFCmanager4-20-again.zip)
(
