### ISSUE TITLE
cannot export ifc file

### ISSUE THREAD

**Issue by huliopalas** [BIM-Tools/SketchUp-IFC-Manager#41]
hello, 
afaik the ifc export button doesn't work
i see the progress bar but then no file is created

i am using a simple file for test. do you know what can cause this issue?

**Comment by janbrouwer** [comment]
Can you check the output of the ruby console? (Extensions -->Developer --> Ruby Console)

**Comment by huliopalas** [comment]
thank you, that's what i get

Error: #<ArgumentError: wrong number of arguments (given 1, expected 2)>
C:/Users/Utente/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/IfcRelAssociatesMaterial_su.rb:26:in `initialize'
C:/Users/Utente/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/material_and_styling.rb:47:in `new'
C:/Users/Utente/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/material_and_styling.rb:47:in `create_material_assoc'
C:/Users/Utente/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/material_and_styling.rb:38:in `initialize'
C:/Users/Utente/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/IfcProduct_su.rb:107:in `new'
C:/Users/Utente/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/IfcProduct_su.rb:107:in `initialize'
C:/Users/Utente/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/parse_xsd.rb:186:in `initialize'
C:/Users/Utente/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/parse_xsd.rb:186:in `initialize'
C:/Users/Utente/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/parse_xsd.rb:186:in `initialize'
C:/Users/Utente/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/ObjectCreator.rb:94:in `new'
C:/Users/Utente/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/ObjectCreator.rb:94:in `create_ifc_entity'
C:/Users/Utente/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/ObjectCreator.rb:55:in `initialize'
C:/Users/Utente/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/IfcModel.rb:224:in `new'
C:/Users/Utente/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/IfcModel.rb:224:in `create_ifc_objects'
C:/Users/Utente/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/IfcModel.rb:128:in `initialize'
C:/Users/Utente/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/bt_ifcmanager/export.rb:60:in `new'
C:/Users/Utente/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/bt_ifcmanager/export.rb:60:in `export'
C:/Users/Utente/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/bt_ifcmanager/loader.rb:129:in `block in <module:IfcManager>'

**Comment by Monalins** [comment]
Hello,
I have the same problem

**Comment by janbrouwer** [comment]
This issue arises when updating the plugin without first removing the old version.
It should be fixed if you delete the file "bt_ifcmanager/lib/lib_ifc/IfcRelAssociatesMaterial_su.rb".
