### ISSUE TITLE
Apparent problem with Sketchup 2023

### ISSUE THREAD

**Issue by valleyarchitect** [BIM-Tools/SketchUp-IFC-Manager#44]
Hi Jan, I just installed SU 2023 - and at startup, I get this "Error Loading File C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/bt_ifcmanager/loader.rb
Error: #<REXML::ParseException: #<NoMethodError: undefined method `<<' for #<Sketchup::Set:0x000001e615b8a838>>
C:/Program Files/SketchUp/SketchUp 2023/Tools/RubyStdLib/rexml/parsers/baseparser.rb:558:in `parse_attributes'
C:/Program Files/SketchUp/SketchUp 2023/Tools/RubyStdLib/rexml/parsers/baseparser.rb:378:in `pull_event'
C:/Program Files/SketchUp/SketchUp 2023/Tools/RubyStdLib/rexml/parsers/baseparser.rb:183:in `pull'
C:/Program Files/SketchUp/SketchUp 2023/Tools/RubyStdLib/rexml/parsers/treeparser.rb:23:in `parse'
C:/Program Files/SketchUp/SketchUp 2023/Tools/RubyStdLib/rexml/document.rb:288:in `build'
C:/Program Files/SketchUp/SketchUp 2023/Tools/RubyStdLib/rexml/document.rb:45:in `initialize'
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/bt_ifcmanager/lib/skc_reader.rb:63:in `new'
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/bt_ifcmanager/lib/skc_reader.rb:63:in `block in set_properties'
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/bt_ifcmanager/lib/rubyzip/zip/file.rb:124:in `open'
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/bt_ifcmanager/lib/skc_reader.rb:59:in `set_properties'
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/bt_ifcmanager/lib/skc_reader.rb:49:in `initialize'
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/bt_ifcmanager/settings.rb:262:in `new'
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/bt_ifcmanager/settings.rb:262:in `block in read_classifications'
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/bt_ifcmanager/settings.rb:260:in `each_pair'
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/bt_ifcmanager/settings.rb:260:in `read_classifications'
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/bt_ifcmanager/settings.rb:171:in `load_settings'
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/bt_ifcmanager/loader.rb:76:in `<module:IfcManager>'
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/bt_ifcmanager/loader.rb:30:in `<module:BimTools>'
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/bt_ifcmanager/loader.rb:29:in `<top (required)>'
C:/Program Files/SketchUp/SketchUp 2023/Tools/extensions.rb:197:in `require'
C:/Program Files/SketchUp/SketchUp 2023/Tools/extensions.rb:197:in `load'
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/bt_ifcmanager.rb:48:in `register_extension'
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/bt_ifcmanager.rb:48:in `<module:IfcManager>'
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/bt_ifcmanager.rb:33:in `<module:BimTools>'
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/bt_ifcmanager.rb:30:in `<top (required)>'
...
Exception parsing
Line: 2
Position: 394
Last 80 unconsumed characters:
>
C:/Program Files/SketchUp/SketchUp 2023/Tools/RubyStdLib/rexml/parsers/baseparser.rb:410:in `rescue in pull_event'
C:/Program Files/SketchUp/SketchUp 2023/Tools/RubyStdLib/rexml/parsers/baseparser.rb:332:in `pull_event'
C:/Program Files/SketchUp/SketchUp 2023/Tools/RubyStdLib/rexml/parsers/baseparser.rb:183:in `pull'
C:/Program Files/SketchUp/SketchUp 2023/Tools/RubyStdLib/rexml/parsers/treeparser.rb:23:in `parse'
C:/Program Files/SketchUp/SketchUp 2023/Tools/RubyStdLib/rexml/document.rb:288:in `build'
C:/Program Files/SketchUp/SketchUp 2023/Tools/RubyStdLib/rexml/document.rb:45:in `initialize'
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/bt_ifcmanager/lib/skc_reader.rb:63:in `new'
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/bt_ifcmanager/lib/skc_reader.rb:63:in `block in set_properties'
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/bt_ifcmanager/lib/rubyzip/zip/file.rb:124:in `open'
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/bt_ifcmanager/lib/skc_reader.rb:59:in `set_properties'
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/bt_ifcmanager/lib/skc_reader.rb:49:in `initialize'
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/bt_ifcmanager/settings.rb:262:in `new'
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/bt_ifcmanager/settings.rb:262:in `block in read_classifications'
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/bt_ifcmanager/settings.rb:260:in `each_pair'
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/bt_ifcmanager/settings.rb:260:in `read_classifications'
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/bt_ifcmanager/settings.rb:171:in `load_settings'
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/bt_ifcmanager/loader.rb:76:in `<module:IfcManager>'
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/bt_ifcmanager/loader.rb:30:in `<module:BimTools>'
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2023/SketchUp/Plugins/bt_ifcmanager/loader.rb:29:in `<top (required)>'
C:/Program Files/SketchUp/SketchUp 2023/Tools/extensions.rb:197:in `require'
..."
I wonder if you have any idea what the issues is ?
Best regards,
PT

**Comment by janbrouwer** [comment]
I think as a temporary solution you can install the rexml gem.

ruby console: "gem install rexml"

I don't have the problem myself currently, I will try on another PC...

**Comment by valleyarchitect** [comment]
Thanks Jan, I'll try that on the offending machine !

All the best,
Patrick Thomas
architecte dplg
*T: +33(0)610045410*

http://www.vivarchi.f <http://www.vivarchi.fr>r

**Comment by valleyarchitect** [comment]
Jan,

I tried that & got this error message:

gem install rexml
Error: #<NameError: undefined local variable or method `rexml' for
main:Object>
<main>:in `<main>'
SketchUp:in `eval'
=> nil

what am I doing wrong ?
sorry, but it's all a bit gobbledeygook to me

thanks,
best regards,

Patrick Thomas
architecte dplg
*T: +33(0)610045410*

http://www.vivarchi.f <http://www.vivarchi.fr>r

**Comment by valleyarchitect** [comment]
Just to be precise,  I downloaded rexml.rb & its rexml folder & they are
both in the plugins folder for SU23...

Patrick Thomas
architecte dplg
*T: +33(0)610045410*

http://www.vivarchi.f <http://www.vivarchi.fr>r

**Comment by janbrouwer** [comment]
I'm sorry @valleyarchitect, I think I sent you in the wrong direction.
I thought the issue was a missing REXML library like I had earlier myself, but reading the errors more thoroughly it even shows REXML is present, the next thing that could have issues is rubyzip.
I updated the bundled version of rubyzip to the latest version in the hope it will fix something I'm not able to replicate myself.

Can you please give this prerelease version a try?
https://github.com/BIM-Tools/SketchUp-IFC-Manager/releases/tag/v4.3.3

**Comment by janbrouwer** [comment]
Issue was caused by another plugin.
