### ISSUE TITLE
v5.0.2 hierarchy issue 

### ISSUE THREAD

**Issue by valleyarchitect** [BIM-Tools/SketchUp-IFC-Manager#51]
Hi,

I've been trying v5.0.2 in SU23.1 & am impressed by the texture/color transfer improvements.
However, I noticed an issue in hierarchy.
Here is the SU file I was working on & the resulting ifc file, plus the same model exported using v3.4.7 of your plugin where there are no issues concerning the hierarchy.
I've also added screenshots so you know what options were active in the preferences before export as ifc.
[00-ESQ.zip](https://github.com/BIM-Tools/SketchUp-IFC-Manager/files/12706302/00-ESQ.zip)

Thanks in advance for any feedback you might have

**Comment by janbrouwer** [comment]
I don't see the 'floating roof' in any of the viewers and checkerd I have currently installed, I will make a new release, can you test if you still see that there? Could it be an issue in eveBIM?
I did fix an issue for IfcRoof used as a container.
I also made a change in version 5 where unclassified objects are grouped inside the first IFC entity higher in the conponent hierarchy, this prevents models without any IFC classifications being merged into one big blob.

**Comment by valleyarchitect** [comment]
Hi Jan, thanks for your feedback.

The ifc exported with 3.4.7 allows for "floating" the roof in eveBIM or
other viewers that have that "exploded view" function, whereas the ifc
exported using 5.0.2 no longer worked...
Yes, I'll gladly test a tweaked version :)

Best regards,
Patrick Thomas
architecte dplg
*T: +33(0)610045410*

http://www.vivarchi.f <http://www.vivarchi.fr>r

**Comment by valleyarchitect** [comment]
Jan,
<img width="1919" alt="IFCManager-347-danseveBIM" src="https://github.com/BIM-Tools/SketchUp-IFC-Manager/assets/70261186/d9500750-7de2-4c04-8346-0578c2f3edaf">
<img width="1921" alt="IFCManager-503" src="https://github.com/BIM-Tools/SketchUp-IFC-Manager/assets/70261186/9ed3183e-8623-4746-a981-bcf55fae92c1">
<img width="1917" alt="IFCManager-503-dans eveBIM" src="https://github.com/BIM-Tools/SketchUp-IFC-Manager/assets/70261186/57bc3bf8-5018-4649-9ad9-49489a27bf88">

I've tried v503 and it's still doing odd things... as you will see from the sketchup screenshot, a whole bunch of "context" is hidden, yet appears in the ifc file opened in eveBIM even though i've not selected the option to export hidden geometry. Furthermore, the roof storey still doesn't lift correctly in the exploded view.
As a comparison, you'll see that an ifc from the same SU model exported with version 347 of your plugin gives good results !
I have no idea why this is happening :(
Thanks anyway,
Best regards,

PT
