### ISSUE TITLE
Hidden objects are exported to IFC when setting 'hidden' is on False

### ISSUE THREAD

**Issue by newteq-aardug** [BIM-Tools/SketchUp-IFC-Manager#54]
First of all, thanks a lot for creating this great tool!
I found a small bug:

My model contains multiple hidden objects.
When I export my model to IFC (both types), the hidden objects are exported and can be seen in the IFC.

I checked the setting 'hidden', but true or false does not have an effect.

**Comment by janbrouwer** [comment]
Should be solved in https://github.com/BIM-Tools/SketchUp-IFC-Manager/releases/tag/v5.0.6
