### ISSUE TITLE
Missing IfcClassificationReference in Tutorial instructions

### ISSUE THREAD

**Issue by daviddelven** [BIM-Tools/SketchUp-IFC-Manager#56]
I found there is a typo in:

IFC Export settings

> Export hidden objects if checked ALL objects are exported, including objects that are hidden or on a hidden layer
> Export classifications: if checked **IfcPresentationLayerAssignments`** are added to objects in IFC
> Export tags/layers as IFC layers: if checked IfcPresentationLayerAssignments are added to objects in IFC
> Export materials: if checked IfcMaterials are added to objects in IFC
> Export colors: if checked color styling is added to objects in IFC
> Improve export speed by using fake GUID's: if unchecked official GUID's are generated, if checked they are just random numbers
> Export dynamic attributes: if checked dynamic component attributes are converted into propertysets when the attribute name is in the right format

When Exporting classification the **IfcClassificationReference** is the one that should be added to objects in IFC, instead of IfcPresentationLayerAssignment which means only Layers.

**Comment by janbrouwer** [comment]
Thanks, improved the docs!
