### ISSUE TITLE
IfcSpace not being exported

### ISSUE THREAD

**Issue by SeppArc** [BIM-Tools/SketchUp-IFC-Manager#59]
Hi,
first I want to thank for your efforts! Great work, keep it up.

I am experiencing an issue with IfcSpaces when having settings to IFC 4. It seems I can assign IfcSpace but when exporting I et an error. Here is the error from the Sketchup Console:

`Error: #<NoMethodError: undefined method `add_space' for #<BimTools::IfcManager::SpatialStructureHierarchy:0x0000000136e7bd78 @ifc=BimTools::IFC4, @spatial_order=[BimTools::IFC4::IfcProject, BimTools::IFC4::IfcSite, BimTools::IFC4::IfcBuilding, BimTools::IFC4::IfcBuildingStorey, BimTools::IFC4::IfcSpace], @ifc_model=#<BimTools::IfcManager::IfcModel:0x00000001234c71c8 @options={:ifc_entities=>false, :hidden=>false, :attributes=>["SU_DefinitionSet", `

This is the simple structure I try to export:
<img width="1009" alt="image" src="https://github.com/BIM-Tools/SketchUp-IFC-Manager/assets/167858566/7a009329-769a-41d4-a386-b72362a3c955">

**Comment by janbrouwer** [comment]
Fixed in https://github.com/BIM-Tools/SketchUp-IFC-Manager/commit/14dfa5ba79a6073210b93001d12c75ef212d5641
