### ISSUE TITLE
May you can allow it for sketchup 2017 too

### ISSUE THREAD

**Issue by YauronBis** [BIM-Tools/SketchUp-IFC-Manager#6]
![sketchup bt_ifcmanager wrong for 2017](https://user-images.githubusercontent.com/39408265/44343843-50f03c00-a48f-11e8-8df0-2c2f965bc31c.png)

as you can see, not allowed for v. 2017 make, and not knowed as signed plugins.

**Comment by Aerilius** [comment]
"Without signature" does not means that it is incompatible, but that this version has not been signed. A signature ensures that the extension comes from the original, registered extension developer and has not been manipulated from a third-party site. It is "extra" security, but without signature an extension is not necessarily insecure.

If you download an extension from Extension Warehouse, it is automatically signed. If you download it from Github, it is not by default (except if Jan uploads it manually to the [signing tool](https://extensions.sketchup.com/en/developer_center/extension_signature), maybe he'll do it for major releases).

**Comment by janbrouwer** [comment]
I still didn't get to looking into the "signing" and "adding to the extension warehouse" things. But the version 2 release is getting quite complete, might be a good time to check those out! :-D
