### ISSUE TITLE
IFC not exported

### ISSUE THREAD

**Issue by SvSchaijk** [BIM-Tools/SketchUp-IFC-Manager#7]
See error below. Do you have any idea how this problem can be solved?
![error export](https://user-images.githubusercontent.com/14818187/47008250-3f977900-d13a-11e8-898f-e987d56e2bf4.png)

**Comment by janbrouwer** [comment]
I think I fixed this error: https://github.com/BIM-Tools/SketchUp-IFC-Manager/commit/a3cf61b465adb15cfe870c15db32de7767bb56e4
