### ISSUE TITLE
Problems with exporting 

### ISSUE THREAD

**Issue by Sjef89** [BIM-Tools/SketchUp-IFC-Manager#71]
Using latest version, export fails without any notification..
![image](https://github.com/user-attachments/assets/f1756146-865a-4a2e-897c-dda52e1fe277)

wenn i export the document, the status in the command line below start to show 25%. but it doesnt finish.
i am using this setting combination

![image](https://github.com/user-attachments/assets/7409fe4b-f739-4a93-8a4c-676abb9021f3)

how can i fix this..?

**Comment by jbrouwerdigibase** [comment]
Can you open the ruby console before export and share the content? Extensions > Developer > Ruby Console
It will probably show some error message.

**Comment by Sjef89** [comment]
This is the Errormessage.. 

i couldnt upload it in one part because of its size..

[fail export IFC Manager part 2.txt](https://github.com/user-attachments/files/17698353/fail.export.IFC.Manager.part.2.txt)
[fail export IFC Manager.txt](https://github.com/user-attachments/files/17698354/fail.export.IFC.Manager.txt)

**Comment by janbrouwer** [comment]
Sorry that was an unnecessary bug... https://github.com/BIM-Tools/SketchUp-IFC-Manager/releases/tag/v5.3.2
