### ISSUE TITLE
Ifc manager not exporting anything (latest version)

### ISSUE THREAD

**Issue by RubenMRJ** [BIM-Tools/SketchUp-IFC-Manager#76]
Quick question, my ifc manager doesnt export anything… no matter what setting i put, theres no file saved afterwards

(note, im even using 5d plus to manage the basic ifc tags and ifc type) my objective is to export an manageable ifc file for engineer use afterwards, if anybody can help i appreciate it

thanks

**Comment by janbrouwer** [comment]
Should be fixed in [release v5.4.0](https://github.com/BIM-Tools/SketchUp-IFC-Manager/releases/tag/v5.4.0)
