### ISSUE TITLE
Problem with export dynamic component to IFC

### ISSUE THREAD

**Issue by nnijmeijer** [BIM-Tools/SketchUp-IFC-Manager#8]
If I want to export a dynamic component in sketchup to IFC, I get the following error code in the Ruby console. This error is also generated if the dynamic component is modeled in a complete BIM project in accordance with the BIM Basis ILS.

![ifc manager extensie foutmelding dynamic component](https://user-images.githubusercontent.com/44203724/47226787-b09c9200-d3c1-11e8-98ea-d2b9abc42425.png)

**Comment by janbrouwer** [comment]
Fixed in Version-2.0 branch [https://github.com/BIM-Tools/SketchUp-IFC-Manager/commit/27cb008ee54a6ef43f1922c0582b5b779aea714a](url)
